//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Chilicki.Commline.Application.Resources {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "15.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class ValidationResources {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal ValidationResources() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("Chilicki.Commline.Application.Resources.ValidationResources", typeof(ValidationResources).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Circular line must start and end in the same stop.
        /// </summary>
        internal static string CircularLineMustStartAndEndInTheSameStop {
            get {
                return ResourceManager.GetString("CircularLineMustStartAndEndInTheSameStop", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Circular line must have at least three stops.
        /// </summary>
        internal static string CircularLineStopsLessThanThree {
            get {
                return ResourceManager.GetString("CircularLineStopsLessThanThree", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Start date is empty.
        /// </summary>
        internal static string DateIsEmpty {
            get {
                return ResourceManager.GetString("DateIsEmpty", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to At least one of given departures is empty.
        /// </summary>
        internal static string DepartureEmpty {
            get {
                return ResourceManager.GetString("DepartureEmpty", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Departure time can&apos;t be less than than the previous departure in the same run.
        /// </summary>
        internal static string DeparturesTimesNotCorrect {
            get {
                return ResourceManager.GetString("DeparturesTimesNotCorrect", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Destination stop is empty.
        /// </summary>
        internal static string EndStopIsEmpty {
            get {
                return ResourceManager.GetString("EndStopIsEmpty", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Invalid stop coordinates.
        /// </summary>
        internal static string InvalidCoordinates {
            get {
                return ResourceManager.GetString("InvalidCoordinates", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Line doesn&apos;t exist.
        /// </summary>
        internal static string LineDoesntExist {
            get {
                return ResourceManager.GetString("LineDoesntExist", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Line is empty.
        /// </summary>
        internal static string LineIsEmpty {
            get {
                return ResourceManager.GetString("LineIsEmpty", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Line name is empty.
        /// </summary>
        internal static string LineNameIsEmpty {
            get {
                return ResourceManager.GetString("LineNameIsEmpty", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Line need to have at least two stops.
        /// </summary>
        internal static string LineStopsLessThanTwo {
            get {
                return ResourceManager.GetString("LineStopsLessThanTwo", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to No departures.
        /// </summary>
        internal static string NoDepartures {
            get {
                return ResourceManager.GetString("NoDepartures", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Only one circular line with the same name can exist.
        /// </summary>
        internal static string OnlyOneCircularLineCanExist {
            get {
                return ResourceManager.GetString("OnlyOneCircularLineCanExist", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Only two one-ways lines with the same name can exist.
        /// </summary>
        internal static string OnlyTwoOneWaysLinesCanExist {
            get {
                return ResourceManager.GetString("OnlyTwoOneWaysLinesCanExist", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Start stop is empty.
        /// </summary>
        internal static string StartStopIsEmpty {
            get {
                return ResourceManager.GetString("StartStopIsEmpty", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Stop doesn&apos;t exist.
        /// </summary>
        internal static string StopDoesntExist {
            get {
                return ResourceManager.GetString("StopDoesntExist", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Stop is connected to line. Delete lines that contain this stop first..
        /// </summary>
        internal static string StopIsConnectedToLine {
            get {
                return ResourceManager.GetString("StopIsConnectedToLine", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Stop is empty.
        /// </summary>
        internal static string StopIsEmpty {
            get {
                return ResourceManager.GetString("StopIsEmpty", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Line can be routed on stops of matching type, for example bus line can only go through bus stops.
        /// </summary>
        internal static string StopLineTypesDoNotMatch {
            get {
                return ResourceManager.GetString("StopLineTypesDoNotMatch", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Stop name is empty.
        /// </summary>
        internal static string StopNameEmpty {
            get {
                return ResourceManager.GetString("StopNameEmpty", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Stops in departures do not match with line stops.
        /// </summary>
        internal static string StopsInDeparturesDoNotMatch {
            get {
                return ResourceManager.GetString("StopsInDeparturesDoNotMatch", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Stop type cannot be edited when it&apos;s in previous type line.
        /// </summary>
        internal static string StopTypeCannotBeEditedWhenItsInPreviousTypeLine {
            get {
                return ResourceManager.GetString("StopTypeCannotBeEditedWhenItsInPreviousTypeLine", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Stop with this id does not exist.
        /// </summary>
        internal static string StopWithIdDoesNotExist {
            get {
                return ResourceManager.GetString("StopWithIdDoesNotExist", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Start time is empty.
        /// </summary>
        internal static string TimeIsEmpty {
            get {
                return ResourceManager.GetString("TimeIsEmpty", resourceCulture);
            }
        }
    }
}
