// <auto-generated />
namespace Chilicki.Commline.Infrastructure.Migrations
{
    using System.CodeDom.Compiler;
    using System.Data.Entity.Migrations;
    using System.Data.Entity.Migrations.Infrastructure;
    using System.Resources;
    
    [GeneratedCode("EntityFramework.Migrations", "6.2.0-61023")]
    public sealed partial class AddStopType : IMigrationMetadata
    {
        private readonly ResourceManager Resources = new ResourceManager(typeof(AddStopType));
        
        string IMigrationMetadata.Id
        {
            get { return "201811031832031_AddStopType"; }
        }
        
        string IMigrationMetadata.Source
        {
            get { return null; }
        }
        
        string IMigrationMetadata.Target
        {
            get { return Resources.GetString("Target"); }
        }
    }
}
