//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Chilicki.Commline.UserInterface.Resources {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "15.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    public class BaseResources {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal BaseResources() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("Chilicki.Commline.UserInterface.Resources.BaseResources", typeof(BaseResources).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Actions.
        /// </summary>
        public static string Actions {
            get {
                return ResourceManager.GetString("Actions", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Affirm.
        /// </summary>
        public static string Affirm {
            get {
                return ResourceManager.GetString("Affirm", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Commline.
        /// </summary>
        public static string AppName {
            get {
                return ResourceManager.GetString("AppName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Cancel.
        /// </summary>
        public static string Cancel {
            get {
                return ResourceManager.GetString("Cancel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Circular.
        /// </summary>
        public static string Circular {
            get {
                return ResourceManager.GetString("Circular", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Clear.
        /// </summary>
        public static string Clear {
            get {
                return ResourceManager.GetString("Clear", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Delete.
        /// </summary>
        public static string Delete {
            get {
                return ResourceManager.GetString("Delete", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Departures.
        /// </summary>
        public static string Departures {
            get {
                return ResourceManager.GetString("Departures", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Error occured.
        /// </summary>
        public static string ErrorOccured {
            get {
                return ResourceManager.GetString("ErrorOccured", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Home Page.
        /// </summary>
        public static string HomePage {
            get {
                return ResourceManager.GetString("HomePage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Lines Editor.
        /// </summary>
        public static string LineEditor {
            get {
                return ResourceManager.GetString("LineEditor", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Loading....
        /// </summary>
        public static string Loading {
            get {
                return ResourceManager.GetString("Loading", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Menu.
        /// </summary>
        public static string Menu {
            get {
                return ResourceManager.GetString("Menu", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to No details map.
        /// </summary>
        public static string NoDetailsMap {
            get {
                return ResourceManager.GetString("NoDetailsMap", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Not Set Yet.
        /// </summary>
        public static string NotSetYet {
            get {
                return ResourceManager.GetString("NotSetYet", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Now.
        /// </summary>
        public static string Now {
            get {
                return ResourceManager.GetString("Now", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to One way.
        /// </summary>
        public static string OneWay {
            get {
                return ResourceManager.GetString("OneWay", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Latitude:.
        /// </summary>
        public static string ReadonlyLatitude {
            get {
                return ResourceManager.GetString("ReadonlyLatitude", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Line Route Type:.
        /// </summary>
        public static string ReadonlyLineRouteType {
            get {
                return ResourceManager.GetString("ReadonlyLineRouteType", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Longitude:.
        /// </summary>
        public static string ReadonlyLongitude {
            get {
                return ResourceManager.GetString("ReadonlyLongitude", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Name:.
        /// </summary>
        public static string ReadonlyName {
            get {
                return ResourceManager.GetString("ReadonlyName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Station Number:.
        /// </summary>
        public static string ReadonlyStationNumber {
            get {
                return ResourceManager.GetString("ReadonlyStationNumber", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Remove.
        /// </summary>
        public static string Remove {
            get {
                return ResourceManager.GetString("Remove", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Save.
        /// </summary>
        public static string Save {
            get {
                return ResourceManager.GetString("Save", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Search.
        /// </summary>
        public static string Search {
            get {
                return ResourceManager.GetString("Search", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Search.
        /// </summary>
        public static string SearchAsAction {
            get {
                return ResourceManager.GetString("SearchAsAction", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Stops Editor.
        /// </summary>
        public static string StopEditor {
            get {
                return ResourceManager.GetString("StopEditor", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Toolbox.
        /// </summary>
        public static string Toolbox {
            get {
                return ResourceManager.GetString("Toolbox", resourceCulture);
            }
        }
    }
}
