//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Chilicki.Commline.UserInterface.Resources {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "15.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    public class EditorResources {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal EditorResources() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("Chilicki.Commline.UserInterface.Resources.EditorResources", typeof(EditorResources).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Add next departure run.
        /// </summary>
        public static string AddNextDepartureRun {
            get {
                return ResourceManager.GetString("AddNextDepartureRun", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Add next return departure run.
        /// </summary>
        public static string AddNextReturnDepartureRun {
            get {
                return ResourceManager.GetString("AddNextReturnDepartureRun", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Are you sure you want to remove this stop?.
        /// </summary>
        public static string AreYouSureRemoveStop {
            get {
                return ResourceManager.GetString("AreYouSureRemoveStop", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Create Line Tool.
        /// </summary>
        public static string CreateLineTool {
            get {
                return ResourceManager.GetString("CreateLineTool", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Use Create Line Tool to create new line.
        /// </summary>
        public static string CreateLineToolDescription {
            get {
                return ResourceManager.GetString("CreateLineToolDescription", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Create Stop Tool.
        /// </summary>
        public static string CreateStopTool {
            get {
                return ResourceManager.GetString("CreateStopTool", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Use Add Stop Tool to add bus stops.
        /// </summary>
        public static string CreateStopToolDescription {
            get {
                return ResourceManager.GetString("CreateStopToolDescription", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Use Departures Tool to establish departures times for lines.
        /// </summary>
        public static string DeparturesDescription {
            get {
                return ResourceManager.GetString("DeparturesDescription", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Departures for.
        /// </summary>
        public static string DeparturesFor {
            get {
                return ResourceManager.GetString("DeparturesFor", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Edit Line Tool.
        /// </summary>
        public static string EditLineTool {
            get {
                return ResourceManager.GetString("EditLineTool", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Use Edit Line Tool to change line name, type, color and path.
        /// </summary>
        public static string EditLineToolDescription {
            get {
                return ResourceManager.GetString("EditLineToolDescription", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Please enter edited details for this stop.
        /// </summary>
        public static string EditStopDetails {
            get {
                return ResourceManager.GetString("EditStopDetails", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Edit Stop Tool.
        /// </summary>
        public static string EditStopTool {
            get {
                return ResourceManager.GetString("EditStopTool", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Use Edit Stop Tool to change stop name and type.
        /// </summary>
        public static string EditStopToolDescription {
            get {
                return ResourceManager.GetString("EditStopToolDescription", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Please, choose line to edit its departures.
        /// </summary>
        public static string GiveLine {
            get {
                return ResourceManager.GetString("GiveLine", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Please enter details for new stop.
        /// </summary>
        public static string GiveStopDetails {
            get {
                return ResourceManager.GetString("GiveStopDetails", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Latitude.
        /// </summary>
        public static string Latitude {
            get {
                return ResourceManager.GetString("Latitude", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Line color.
        /// </summary>
        public static string LineColor {
            get {
                return ResourceManager.GetString("LineColor", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Please enter edited details for this line.
        /// </summary>
        public static string LineEdition {
            get {
                return ResourceManager.GetString("LineEdition", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Line name.
        /// </summary>
        public static string LineName {
            get {
                return ResourceManager.GetString("LineName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Line number.
        /// </summary>
        public static string LineNumber {
            get {
                return ResourceManager.GetString("LineNumber", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Line route type.
        /// </summary>
        public static string LineRouteType {
            get {
                return ResourceManager.GetString("LineRouteType", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Line type.
        /// </summary>
        public static string LineType {
            get {
                return ResourceManager.GetString("LineType", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Longitude.
        /// </summary>
        public static string Longitude {
            get {
                return ResourceManager.GetString("Longitude", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Please enter details for new line.
        /// </summary>
        public static string NewLineCreation {
            get {
                return ResourceManager.GetString("NewLineCreation", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Remove Line Tool.
        /// </summary>
        public static string RemoveLineTool {
            get {
                return ResourceManager.GetString("RemoveLineTool", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Use Remove Line Tool to remove line from the map.
        /// </summary>
        public static string RemoveLineToolDescription {
            get {
                return ResourceManager.GetString("RemoveLineToolDescription", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Remove Stop Tool.
        /// </summary>
        public static string RemoveStopTool {
            get {
                return ResourceManager.GetString("RemoveStopTool", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Use Remove Stop Tool to remove unused stops from the map.
        /// </summary>
        public static string RemoveStopToolDescription {
            get {
                return ResourceManager.GetString("RemoveStopToolDescription", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Station number.
        /// </summary>
        public static string StationNumber {
            get {
                return ResourceManager.GetString("StationNumber", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Stop name.
        /// </summary>
        public static string StopName {
            get {
                return ResourceManager.GetString("StopName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Stop type.
        /// </summary>
        public static string StopType {
            get {
                return ResourceManager.GetString("StopType", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Successfully saved departures.
        /// </summary>
        public static string SuccessfullySavedDepartures {
            get {
                return ResourceManager.GetString("SuccessfullySavedDepartures", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Successfully saved lines.
        /// </summary>
        public static string SuccessfullySavedLines {
            get {
                return ResourceManager.GetString("SuccessfullySavedLines", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Successfully saved stops.
        /// </summary>
        public static string SuccessfullySavedStops {
            get {
                return ResourceManager.GetString("SuccessfullySavedStops", resourceCulture);
            }
        }
    }
}
