//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Chilicki.Commline.UserInterface.Resources {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "15.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    public class EditorResources {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal EditorResources() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("Chilicki.Commline.UserInterface.Resources.EditorResources", typeof(EditorResources).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Add next departure run.
        /// </summary>
        public static string AddNextDepartureRun {
            get {
                return ResourceManager.GetString("AddNextDepartureRun", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Add next return departure run.
        /// </summary>
        public static string AddNextReturnDepartureRun {
            get {
                return ResourceManager.GetString("AddNextReturnDepartureRun", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Use Bus Stop Tool to add, edit or delete bus stops.
        /// </summary>
        public static string BusStopToolDescription {
            get {
                return ResourceManager.GetString("BusStopToolDescription", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Create Line Tool.
        /// </summary>
        public static string CreateLineTool {
            get {
                return ResourceManager.GetString("CreateLineTool", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Create Stop Tool.
        /// </summary>
        public static string CreateStopTool {
            get {
                return ResourceManager.GetString("CreateStopTool", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Use Departures Tool to establish departures times for lines.
        /// </summary>
        public static string DeparturesDescription {
            get {
                return ResourceManager.GetString("DeparturesDescription", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Departures for.
        /// </summary>
        public static string DeparturesFor {
            get {
                return ResourceManager.GetString("DeparturesFor", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Please, choose line to edit its departures.
        /// </summary>
        public static string GiveLine {
            get {
                return ResourceManager.GetString("GiveLine", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Please enter details for new stop.
        /// </summary>
        public static string GiveStopDetails {
            get {
                return ResourceManager.GetString("GiveStopDetails", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Line color.
        /// </summary>
        public static string LineColor {
            get {
                return ResourceManager.GetString("LineColor", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Line name.
        /// </summary>
        public static string LineName {
            get {
                return ResourceManager.GetString("LineName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Line number.
        /// </summary>
        public static string LineNumber {
            get {
                return ResourceManager.GetString("LineNumber", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Line route type.
        /// </summary>
        public static string LineRouteType {
            get {
                return ResourceManager.GetString("LineRouteType", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Line type.
        /// </summary>
        public static string LineType {
            get {
                return ResourceManager.GetString("LineType", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Please enter details for new line.
        /// </summary>
        public static string NewLineCreation {
            get {
                return ResourceManager.GetString("NewLineCreation", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Station number.
        /// </summary>
        public static string StationNumber {
            get {
                return ResourceManager.GetString("StationNumber", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Stop name.
        /// </summary>
        public static string StopName {
            get {
                return ResourceManager.GetString("StopName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Stop type.
        /// </summary>
        public static string StopType {
            get {
                return ResourceManager.GetString("StopType", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Successfully saved departures.
        /// </summary>
        public static string SuccessfullySavedDepartures {
            get {
                return ResourceManager.GetString("SuccessfullySavedDepartures", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Successfully saved lines.
        /// </summary>
        public static string SuccessfullySavedLines {
            get {
                return ResourceManager.GetString("SuccessfullySavedLines", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Successfully saved stops.
        /// </summary>
        public static string SuccessfullySavedStops {
            get {
                return ResourceManager.GetString("SuccessfullySavedStops", resourceCulture);
            }
        }
    }
}
