//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Chilicki.Commline.UserInterface.Resources {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "15.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    public class SettingsResources {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal SettingsResources() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("Chilicki.Commline.UserInterface.Resources.SettingsResources", typeof(SettingsResources).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Back to default settings.
        /// </summary>
        public static string BackToDefaultSettings {
            get {
                return ResourceManager.GetString("BackToDefaultSettings", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Center map point latitude.
        /// </summary>
        public static string CenterPointLatitude {
            get {
                return ResourceManager.GetString("CenterPointLatitude", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Center map point longitude.
        /// </summary>
        public static string CenterPointLongitude {
            get {
                return ResourceManager.GetString("CenterPointLongitude", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Departures copy times option 1.
        /// </summary>
        public static string CopyTimesOption1 {
            get {
                return ResourceManager.GetString("CopyTimesOption1", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Departures copy times option 2.
        /// </summary>
        public static string CopyTimesOption2 {
            get {
                return ResourceManager.GetString("CopyTimesOption2", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Departures copy times option 3.
        /// </summary>
        public static string CopyTimesOption3 {
            get {
                return ResourceManager.GetString("CopyTimesOption3", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Minimum zoom stops start to appear.
        /// </summary>
        public static string MinimumZoomStopsAppear {
            get {
                return ResourceManager.GetString("MinimumZoomStopsAppear", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Starting map zoom.
        /// </summary>
        public static string StartZoom {
            get {
                return ResourceManager.GetString("StartZoom", resourceCulture);
            }
        }
    }
}
